"""initial

Revision ID: 47adf491c6c9
Revises: 
Create Date: 2024-09-02 01:30:42.862433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47adf491c6c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groomers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('hours', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('pet_walker', sa.Boolean(), nullable=True),
    sa.Column('pet_sitter', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_pets_owner_id_owners')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_time', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('isCompleted', sa.Boolean(), nullable=True),
    sa.Column('groomer_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groomer_id'], ['groomers.id'], name=op.f('fk_appointments_groomer_id_groomers')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_appointments_owner_id_owners')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_appointments_pet_id_pets')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=True),
    sa.Column('isCompleted', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_jobs_owner_id_owners')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_jobs_pet_id_pets')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_jobs_worker_id_workers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('appointments')
    op.drop_table('pets')
    op.drop_table('workers')
    op.drop_table('owners')
    op.drop_table('groomers')
    # ### end Alembic commands ###
