"""empty message

Revision ID: 54ac1699e27c
Revises: b3b139a9e767
Create Date: 2024-08-27 14:54:34.281342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ac1699e27c'
down_revision = 'b3b139a9e767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groomer_pets', schema=None) as batch_op:
        batch_op.alter_column('appointment_time',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groomer_pets', schema=None) as batch_op:
        batch_op.alter_column('appointment_time',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
