"""empty message

Revision ID: b3b139a9e767
Revises: 32eb22f57c12
Create Date: 2024-08-21 16:20:13.249735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b139a9e767'
down_revision = '32eb22f57c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_pets', schema=None) as batch_op:
        batch_op.drop_column('job_type')

    # ### end Alembic commands ###
